### ISSUE TITLE
Tried to register two views with the same name RNCMaskedView, js engine: hermes

### ISSUE THREAD

**Issue by wtricks** [creativetimofficial/soft-ui-react-native#27]
# Failure Information (for bugs)

 ERROR  Invariant Violation: Tried to register two views with the same name RNCMaskedView, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

## Steps to Reproduce

Just run `npm run start`

**Comment by JuanCorzo** [comment]
Hello friend, did you get a solution? I have the same problem @wtricks

**Comment by christychacko** [comment]
deleting node_modules/@react-native-community/masked-view folder worked for me since it's a duplicate of node_modules/@react-native-masked-view/masked-view

Originally posted by @erickwarui28 in https://github.com/creativetimofficial/soft-ui-react-native/issues/32#issuecomment-2408531150_
