### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCMaskedView, at startup

### ISSUE THREAD

**Issue by mattiabonzi** [creativetimofficial/soft-ui-react-native#31]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed (it has been filed, but closed without any answer due to respsecting the issue format)
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The app start as described in the documentation.

# Current Behavior

The app does not start correctly and crash as soon the building process finish.

# Failure Information (for bugs)

The app crash with the following two error, the template has not been modified, just downloaded and tried to start as per documentation.

```
ERROR  Invariant Violation: Tried to register two views with the same name RNCMaskedView, js engine: hermes

ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

## Steps to Reproduce

1) Download the template from Creative Tim website.
2) Open a terminal and enter into the template forlder (root folder).
3) Run `npm install`
4) Run `npm start`
5) Press "a" to open the app on the connected Android device (the device is connected correctly, and all permission has been granted)

## Context

* Device: Xiaomi Note 
* Operating System: Android 13 | Mac Os 14.3.1
* Browser and Version: Does not apply, I'm running it on physical device

**No code as been modified, no file has been moved, just downloaded and tried to run as per documentation.**

## Failure Logs

```
soft-ui-pro-react-native % npm start

> start
> ANDROID_HOME=/opt/homebrew/Caskroom/android-sdk/4333796 expo start

Starting project at /Users/mattiabonzi/Progetti/farmshop/soft-ui-pro-react-native
Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ▀▀▄ ▄██ █ ▄▄▄▄▄ █
█ █   █ ███ ▄▄ █▄ █ █   █ █
█ █▄▄▄█ █ ▄▄ █▄██▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀ █▄▀ █▄▄▄▄▄▄▄█
█▄▄ █▀ ▄█▄  ██▀ ▀▄▄ ▄▄██  █
██▀ █▀▀▄ █▀█▄██▄▄██▀▄█▄▄█▄█
█▄▀ ██▀▄█ ▄█▄ █ ▀█  ███▀ ▀█
█▄▄▄█▀█▄▄█▀▄▀ ▄    ▄█ ▄█▀▄█
█▄▄█▄▄▄▄▄ ▄▀█▄▀ █ ▄▄▄  ▀█ █
█ ▄▄▄▄▄ █▀▀█▄▄▄ █ █▄█ ██▀▄█
█ █   █ ██▄▄ ██ ▄▄▄▄   ▀ ██
█ █▄▄▄█ █ ▄ ▄▄▄▄ ▀▀█ ▄██▄▄█
█▄▄▄▄▄▄▄█▄▄█▄██▄▄▄▄█▄▄███▄█

› Metro waiting on exp://192.168.9.110:19000
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
› Opening exp://192.168.9.110:19000 on 23021RAA2Y
› Press ? │ show all commands
Android Bundling complete 1804ms
 ERROR  Invariant Violation: Tried to register two views with the same name RNCMaskedView, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by JuanCorzo** [comment]
Hello friend, did you get a solution? I have the same problem @mattiabonzi

**Comment by mattiabonzi** [comment]
@JuanCorzo, no I switched to another theme.
Follow this other thread, as this one is closed https://github.com/creativetimofficial/soft-ui-react-native/issues/32
