### ISSUE TITLE
Failed to launch the demo version in a browser

### ISSUE THREAD

**Issue by w8ze-devel** [creativetimofficial/soft-ui-react-native#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Checkouting, installing dependencies and running project should work both in mobile and web.

# Current Behavior

Error while launching the web version. Please see below

# Failure Information (for bugs)

> ‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
> Web Bundling complete 6048ms
> ./node_modules/@react-native-community/masked-view/js/MaskedView.js:14:22
> "export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
>   12 | import { View, StyleSheet, requireNativeComponent } from 'react-native';
>   13 |
> > 14 | const RNCMaskedView = requireNativeComponent<any>('RNCMaskedView');
>      |                      ^
>   15 |
>   16 | import { type MaskedViewProps } from './MaskedViewTypes';

## Steps to Reproduce

1. checkout from github  https://github.com/creativetimofficial/soft-ui-react-native
2. npm install
3. expo start
4. Run in Web Browser

## Context

Last version of expo installed. LTS version of node installed.

* Device: Chrome
* Operating System: Windows 10
* Browser and Version: Latest version of chrome

## Failure Logs

Please see the logs above.

**Comment by hetmann** [comment]
@w8ze-devel currently the web version is not fully supported.

**Comment by w8ze-devel** [comment]
@hetmann Could you please clarify if the source code in the product package include Typescript source code please ?

https://www.creative-tim.com/product/soft-ui-pro-react-native/?ref=suprn-landing-nav

I plan to buy the Freelancer package to use it on my app.

**Comment by hetmann** [comment]
@w8ze-devel yes, TS is fully supported, you can see all the existing types for:
- [components & theme](https://github.com/creativetimofficial/soft-ui-react-native/tree/main/src/constants/types)
- [screens](https://github.com/creativetimofficial/soft-ui-react-native/tree/main/src/screens)
