### ISSUE TITLE
[Bug] Failed to launch the demo version in a browser 

### ISSUE THREAD

**Issue by w8ze-devel** [creativetimofficial/soft-ui-react-native#5]
### Version
1.0.0
### Reproduction link
https://github.com/creativetimofficial/soft-ui-react-native
### Operating System
Windows 10
### Device
Browser. Chrome
### Browser & Version
Chrome Version 95.0.4638.69
### Steps to reproduce
checkout from github https://github.com/creativetimofficial/soft-ui-react-native
npm install
expo start
Run in Web Browser
### What is expected?
Run the demo in a browser
### What is actually happening?
Error in logs :

Web Bundling complete 6048ms
./node_modules/@react-native-community/masked-view/js/MaskedView.js:14:22
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
  12 | import { View, StyleSheet, requireNativeComponent } from 'react-native';
  13 |
> 14 | const RNCMaskedView = requireNativeComponent<any>('RNCMaskedView');
     |                      ^
  15 |
  16 | import { type MaskedViewProps } from './MaskedViewTypes';

---

**Comment by w8ze-devel** [comment]
Hello,

I'm interested in buying the UI Kit. If someone could help fix this problem.

Thanks

**Comment by jsmaroc** [comment]
no support for Web ( check description https://docs.expo.dev/versions/latest/sdk/masked-view/)
